---
title: "flat_minimal.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
library(glue)
```

<!--
You need to run the 'description' chunk in the '0-dev_history.Rmd' file before continuing your code there.
-->

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

# Get a message with a fur color

You can get a message with the fur color of interest with `get_message_fur_color()`

```{r development-get_message_fur_color}
message("We will focus on Cinnamon squirrels")

primary_fur_color <- "Cinnamon"
primary_fur_color <- "Black"
message(glue("We will focus on {primary_fur_color} squirrels"))
```


```{r function-get_message_fur_color}
#' Send a message with the squirrel color of interest
#' 
#' @param primary_fur_color A character string corresponding to primary fur color. 
#'
#' @return Nothing. It is used for its side effect of sending a message.
#' 
#' @importFrom glue glue
#' @export
get_message_fur_color <- function(primary_fur_color){
  if(!(primary_fur_color %in% c("Gray","Cinnamon","Black"))){
    stop("primary colour is not a character")
  }
  message(
    glue("We will focus on {primary_fur_color} squirrels")
  )
}
```


```{r example-get_message_fur_color}
get_message_fur_color(primary_fur_color = "Blue")
```


```{r tests-get_message_fur_color}
test_that("get_message_fur_color works", {
  expect_message(
    object = get_message_fur_color(primary_fur_color = "Cinnamon"),
    regexp = "We will focus on Cinnamon squirrels"
  )
   expect_error(
    object = get_message_fur_color(primary_fur_color = "Blue"),
    regexp = "primary colour is not a character"
  )
})


```



```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(
  flat_file = "dev/flat_minimal.Rmd", 
  vignette_name = "Study the squirrels"
)
```
