# WARNING - Generated by {fusen} from /dev/flat_minimal.Rmd: do not edit by hand

#' my_fun Title
#'
#' @return 1
#' @export
#'
#' @examples
#' get_message_fur_colour("Cinnamon")
get_message_fur_colour <- function(primary_fur_color) {
  message(glue("We will focus on {primary_fur_color} squirrels"))
}
