# WARNING - Generated by {fusen} from /dev/flat_minimal.Rmd: do not edit by hand

#' Send a message with the squirrel color of interest
#' 
#' @param primary_fur_color A character string corresponding to primary fur color. 
#'
#' @return Nothing. It is used for its side effect of sending a message.
#' 
#' @importFrom glue glue
#' @export
#' @examples
#' get_message_fur_color(primary_fur_color = "Black")
get_message_fur_color <- function(primary_fur_color){
  message(
    glue("We will focus on {primary_fur_color} squirrels")
  )
}
